(setq a 0)
(loop 
   (setq a (+ a 1))
   (write a)
   (terpri)
   (when (> a 17) (return a))
)
(print "loop")
(loop for a from 10 to 20
   do (print a)
)
(print "-----------------------------")
(print "do")
(do ((x 0 (+ 2 x))
   (y 20 ( - y 2)))
   ((= x y)(- x y))
   (format t "~% x = ~d  y = ~d" x y)
)
(print "-----------------------------")
(print "dotimes")
(dotimes (n 11)
    (print n) (prin1 (* n n))
)
(print "-----------------------------")
(print "dolist")
(dolist (n '(1 2 3 4 5 6 7 8 9))
   (format t "~% Number: ~d Square: ~d" n (* n n))
)